# Generated by Django 2.0.2 on 2019-10-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_auto_20190930_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
