# Generated by Django 2.0.2 on 2019-09-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190918_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='catagorys',
        ),
        migrations.AddField(
            model_name='products',
            name='catagorys',
            field=models.TextField(blank=True, null=True),
        ),
    ]
