# Generated by Django 2.0.2 on 2019-09-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190918_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
