# Generated by Django 2.0.2 on 2019-09-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='url',
        ),
    ]
