# Generated by Django 2.0.2 on 2019-09-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_products_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='detail',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='seller',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
